version: "3.8"

services:
  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minioku
    networks:
      - mynetwork
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: supersecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/data"

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginxku
    container_name: loginminio
    networks:
      - mynetwork
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

volumes:
  minio_data:

networks:
  mynetwork:
    external: true
